package ru.vk.itmo.test.vadimershov.exceptions;

public class DaoException extends RuntimeException {

    public DaoException(Throwable cause) {
        super(cause);
    }
}
