package ru.vk.itmo.test.viktorkorotkikh.dao.exceptions;

public class UnexpectedIOException extends RuntimeException {
    public UnexpectedIOException(Throwable cause) {
        super(cause);
    }
}
